server:
  port: 8080
spring:
  application:
    name: mybatiesPlus
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: url
    username: username
    password: password